from enum import Enum

MAX_LENGTH_TITLE = 200
MAX_LENGTH_NAME = 100
MAX_LENGTH_SUMMARY = 1000
MAX_LENGTH_ISBN = 13
MAX_LENGTH_IMPRINT = 200
MAX_LENGTH_STATUS = 1
MAX_DISPLAY_GENRE = 3
NUM_BOOK_VIEW = 10  # Số lượng sách hiển thị trên mỗi trang

class LOAN_STATUS(Enum):
    MAINTENANCE = 'm'
    ON_LOAN = 'o'
    AVAILABLE = 'a'
    RESERVED = 'r'
    
